/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Customization: typeof import('./lib/components/customization.vue')['default']
    DefaultDirectory: typeof import('./lib/components/defaultDirectory.vue')['default']
    GreetComponent: typeof import('./lib/components/greet-component.vue')['default']
    Hotbar: typeof import('./lib/components/hotbar.vue')['default']
    LoginPage: typeof import('./lib/components/loginPage.vue')['default']
    Notifications: typeof import('./lib/components/notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./lib/components/settings.vue')['default']
    TagEditorView: typeof import('./lib/components/tagEditorView.vue')['default']
    'TagEditorView.': typeof import('./lib/components/tagEditorView..vue')['default']
    UserMenu: typeof import('./lib/components/userMenu.vue')['default']
  }
}
