export enum ErrorCode {
  NONE = 'NONE',
  EMPTY_CHUNKS = 'EMPTY_CHUNKS',
  UNRECOGNIZED_TOKEN = 'UNRECOGNIZED_TOKEN',
  INVALID_CHUNK_DECLARATION = 'INVALID_CHUNK_DECLARATION',
  MISSING_CHUNK_TYPE = 'MISSING_CHUNK_TYPE',
  UNKNOWN_CHUNK_TYPE = 'UNKNOWN_CHUNK_TYPE',
  INVALID_TOKEN_IN_CHUNK = 'INVALID_TOKEN_IN_CHUNK',
  MISSING_TOKEN = 'MISSING_TOKEN',
  INVALID_ID_TOKEN = 'INVALID_ID_TOKEN',
  INVALID_HASH_HISTORY = 'INVALID_HASH_HISTORY',
  MISSING_META_FOR_FILE = 'MISSING_META_FOR_FILE',
  FILE_META_HASH_MISMATCH = 'FILE_META_HASH_MISMATCH',
}
